{
 "title": "FleetOps- Métier",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Taux d'erreurs 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{status=~\"5..\"}[5m]) / rate(http_requests_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latence p95 par endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "rate(http_requests_total[5m])", "legendFormat": "__auto" },
    {}
   ]
  }
 ]
}